### PR TITLE
JBEHAVE-1135 Run story-level Given stories only if story contains scenarios

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by valfirst** [comment]
Is there any chance to review and merge the changes to the master so that they will be included in the upcoming JBehave 4.1 release?

**Comment by maurotalevi** [comment]
This patch cannot be applied as it fails the tests

**Comment by valfirst** [comment]
Could you please point which tests fail? I run `mvn install -Pexamples`, build passes.

**Comment by maurotalevi** [comment]
Tests run: 16, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE! - in org.jbehave.core.steps.StepsBehaviour
shouldProvideStepsToBePerformedBeforeAndAfterScenariosWithNoFailureOccuring(org.jbehave.core.steps.StepsBehaviour)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.jbehave.core.steps.StepsBehaviour.shouldProvideStepsToBePerformedBeforeAndAfterScenariosWithNoFailureOccuring(StepsBehaviour.java:178)

shouldProvideStepsToBeNotPerformedAfterScenarioUponOutcome(org.jbehave.core.steps.StepsBehaviour)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.jbehave.core.steps.StepsBehaviour.shouldProvideStepsToBeNotPerformedAfterScenarioUponOutcome(StepsBehaviour.java:204)

shouldProvideStepsToBePerformedBeforeAndAfterScenariosWithFailureOccuring(org.jbehave.core.steps.StepsBehaviour)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.jbehave.core.steps.StepsBehaviour.shouldProvideStepsToBePerformedBeforeAndAfterScenariosWithFailureOccuring(StepsBehaviour.java:154)


Results :

Failed tests: 
  StepsBehaviour.shouldProvideStepsToBeNotPerformedAfterScenarioUponOutcome:204 
Expected: is <true>
     but: was <false>
  StepsBehaviour.shouldProvideStepsToBePerformedBeforeAndAfterScenariosWithFailureOccuring:154 
Expected: is <true>
     but: was <false>
  StepsBehaviour.shouldProvideStepsToBePerformedBeforeAndAfterScenariosWithNoFailureOccuring:178 
Expected: is <true>
     but: was <false>

Tests run: 544, Failures: 3, Errors: 0, Skipped: 1

**Comment by valfirst** [comment]
@maurotalevi , thank you for your help!
I tried to debug mentioned tests, but changed code is not invoked during run, so looks like these changes is not a reason of test failures.

Then I cloned master branch of jbehave-core repository and tried to build the project several times:
```
git clone https://github.com/jbehave/jbehave-core.git
cd jbehave-core
mvn install -s settings.xml     
```

3 mentioned tests fail randomly at different runs (pass - fail - pass - pass...). I wasn't able to reproduce the issue in Eclipse IDE.

**Comment by maurotalevi** [comment]
Yes, you are quite right, seems a random failure even without the patch.  I'll  try to have a look at it.

**Comment by valfirst** [comment]
Closing PR, changes are added to the [master](https://github.com/jbehave/jbehave-core/commit/81a94954a2b83b6d4f44b6d210d56a3909bbb24f)

**Pull request closed without merging**
