### PR TITLE
JBEHAVE-1374 Upgrade Spring to 5.2.0 and AspectJ to 1.9.4

### PR DESCRIPTION
**Pull request by berryh**
Due to upgrading Spring Framework in our application, we would like for JBehave to use the same, or at least somewhat latest, version of Spring. Doing this also requires an upgrade of AspectJ.

### CODE REVIEW

**Comment by valfirst** [comment]
@berryh the build is failed, please, fix compilation errors

**Comment by berryh** [comment]
@valfirst All tests are passing now. There are still some OS-related issues with the tests. I am running Windows and the JRuby test does not work properly for example. It looks like an issue with line ending character difference between Windows and Linux. I fixed one related issue, but it might be worth looking into this, sometime in the future.

**Comment by valfirst** [comment]
@berryh, I'm just contributor of the project, the maintainer of the project is @maurotalevi. You can find the official contribution guide at https://jbehave.org/how-to-contribute.html. You should create a new Jira issue and follow the described steps. 
My personal recommendation is to squash some commits to make them atomic and independent

**Comment by maurotalevi** [comment]
I second that.   Please separate improvements to the example from changes in the jbehave-spring module. 

Bear in mind that any changes to the dependency version (eg spring-core) in jbehave-spring should be justified by functionality in the module itself. 

Otherwise the versions of the dependencies can be changed accordingly only in the example.

**Comment by maurotalevi** [comment]
Pulled in 4.6.2

**Pull request closed without merging**
