### PR TITLE
JBEHAVE-1133 ExamplesTableFactory shouldn't use custom default ResourceLoader-s

### PR DESCRIPTION
**Pull request by valfirst**
This change is the first step to removing custom default configuration objects (Keywords, ResourcesLoader-s and etc.). 
- It will help to support JBehave customization cases: configure once and use everywhere, less potential bugs related to customization 
- It may improve performance a bit (no duplicate object creations)

### CODE REVIEW

**Comment by valfirst** [comment]
Is there any chance to review and merge the changes to the master so that they will be included in the upcoming JBehave 4.1 release? 

I was needed to load story files from classpath and generate examples tables on runtime basing on DB data, but was not able to override default resource loader of examples tables. So the main reason of these changes is to eliminate existing shortcoming.

**Comment by maurotalevi** [comment]
Hi, the scope of the PR is too big compared to the stated aim.   In particular, the fact it tries to inject the Configuration object in the components, instead of the individual dependencies.  

Can you provide an example of how you'd need to have the resource loader configurable so we can try to satisfy it?

**Comment by valfirst** [comment]
Hi, the original issue is not in resource loader configuration (in general, I implemented some types of resource loader for examples tables that load data from file system using some custom rules, from DB-s, from RESTful APIs). The original issue is that ExamplesTableFactory defines own custom resource loader:
- https://github.com/jbehave/jbehave-core/blob/master/jbehave-core/src/main/java/org/jbehave/core/model/ExamplesTableFactory.java#L43
- https://github.com/jbehave/jbehave-core/blob/master/jbehave-core/src/main/java/org/jbehave/core/model/ExamplesTableFactory.java#L51
- https://github.com/jbehave/jbehave-core/blob/master/jbehave-core/src/main/java/org/jbehave/core/model/ExamplesTableFactory.java#L55

Removal of this custom resource loaders brings chains of changes in multiple classes that use the constructors with default loaders.
If you don't like the idea of Configuration injection in the components, I will refactor the changes.

**Comment by valfirst** [comment]
Finally I've found time to redesign the solution.

@maurotalevi , could you please review the change?

**Comment by valfirst** [comment]
@maurotalevi, could you please review the change?

**Comment by valfirst** [comment]
@maurotalevi, could you please review the change?

**Comment by valfirst** [comment]
@maurotalevi, could you please review the changes?

**Comment by valfirst** [comment]
[Merged](https://github.com/jbehave/jbehave-core/commit/a79f1bdf1551bf122ea3d7b66914d3af3ebf5fb1). @maurotalevi , thank you!

**Comment by valfirst** [comment]
New pull request: https://github.com/jbehave/jbehave-core/pull/152

**Pull request closed without merging**
