### PR TITLE
JBEHAVE-1369 Fix build on travis-ci

### PR DESCRIPTION
**Pull request by valfirst**
More details: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766

### CODE REVIEW

**Comment by pzygielo** [comment]
Why not allow routing job to xenial but switch to OpenJDK instead?

**Comment by valfirst** [comment]
@pzygielo what are pros and cons?

**Comment by pzygielo** [comment]
Pro: travis still has freedom to choose worker, like before.

Announcement about routing projects to xenial: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment.

**Comment by valfirst** [comment]
@pzygielo switch from OracleJDK to OpenJDK may bring new unexpected issues, I believe it should be done in scope of separate ticket (not ticket related to fixing CI build). The current fix addresses the changes in CI system and makes build green again without changes in CI configuration matrix. However I do see your point, please, feel free to open new PR, @maurotalevi will take a decision.

**Comment by pzygielo** [comment]
> The current fix addresses the changes in CI system and makes build green again without changes in CI configuration matrix. 

True, agreed.

**Comment by valfirst** [comment]
The changes have been added to `master` branch: 9d7ae17842c9c5855f27e81adf9609d1d12979fc

**Pull request closed without merging**
