### PR TITLE
[JBEHAVE-1160] Fix pom to be compatible with Jenkins.

### PR DESCRIPTION
**Pull request by christ66**
To add some more context to this issue the current Jenkins jbehave plugin throws the following exception:

```
Failed to scout org.jbehave.jenkins.JBehavePluginType$DescriptorImpl
java.lang.InstantiationException: java.lang.NoClassDefFoundError: com/thalesgroup/dtkit/metrics/hudson/api/descriptor/TestTypeDescriptor
    at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
    at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:663)
    at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:339)
    at hudson.ExtensionList.load(ExtensionList.java:300)
    at hudson.ExtensionList.ensureLoaded(ExtensionList.java:253)
    at hudson.ExtensionList.iterator(ExtensionList.java:143)
    at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:338)
    at hudson.ExtensionList.load(ExtensionList.java:300)
    at hudson.ExtensionList.ensureLoaded(ExtensionList.java:253)
    at hudson.ExtensionList.getComponents(ExtensionList.java:154)
    at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:182)
    at hudson.ExtensionList.ensureLoaded(ExtensionList.java:253)
    at hudson.ExtensionList.iterator(ExtensionList.java:143)
    at org.jenkinsci.plugins.xunit.AliasInitializer.addAliases(AliasInitializer.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:105)
    at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:169)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
    at jenkins.model.Jenkins$7.runTask(Jenkins.java:886)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/thalesgroup/dtkit/metrics/hudson/api/descriptor/TestTypeDescriptor
```

See http://stackoverflow.com/questions/26861855/jenkins-jbehave-plugin-installation-failed-classnotfoundexception-dtkit-testty for more information.

### CODE REVIEW

**Comment by marcesher** [comment]
PLEASE review and merge this. It's preventing all Jenkins users from upgrading the xunit plugin.

Thank you!

**Comment by maurotalevi** [comment]
This PR cannot be merged as it does not compile.  Please review it and recreate a new PR:

[INFO] Generating /Users/mauro/git/jbehave/core/jbehave-jenkins-plugin/target/test-classes/the.hpl
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.378 s
[INFO] Finished at: 2016-04-25T19:17:52+02:00
[INFO] Final Memory: 42M/430M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:1.117:test-hpl (default-test-hpl) on project jbehave-jenkins-plugin: Error preparing the manifest: Failed to open artifact org.apache.ant:ant:jar:1.8.3:provided at /Users/mauro/.m2/repository/org/apache/ant/ant/1.8.3/ant-1.8.3.jar: 1 problem was encountered while building the effective model for org.apache.ant:ant:1.8.3
[ERROR] [FATAL] Non-parseable POM /Users/mauro/.m2/repository/org/apache/ant/ant-parent/1.8.3/ant-parent-1.8.3.pom: only whitespace content allowed before start tag and not 0 (position: START_DOCUMENT seen 0... @1:1)  @ /Users/mauro/.m2/repository/org/apache/ant/ant-parent/1.8.3/ant-parent-1.8.3.pom, line 1, column 1
[ERROR] for project org.apache.ant:ant:1.8.3 for project org.apache.ant:ant:1.8.

**Comment by christ66** [comment]
@maurotalevi I ran it locally and it was able to build. The error message you are receiving above is caused by your maven repository being partially corrupt. If you open the file ` /Users/mauro/.m2/repository/org/apache/ant/ant-parent/1.8.3/ant-parent-1.8.3.pom` the file will contain invalid characters for xml. I would recommend either deleting this pom file or running the maven command with `-U` to redownload the dependencies.

I ran with mvn package:

```
➜  jbehave-jenkins-plugin git:(jenkins) mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JBehave Jenkins Plugin 4.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:validate (default-validate) @ jbehave-jenkins-plugin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ jbehave-jenkins-plugin ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ jbehave-jenkins-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ jbehave-jenkins-plugin ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- access-modifier-checker:1.7:enforce (default-enforce) @ jbehave-jenkins-plugin ---
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:insert-test (default-insert-test) @ jbehave-jenkins-plugin ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ jbehave-jenkins-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ jbehave-jenkins-plugin ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:test-hpl (default-test-hpl) @ jbehave-jenkins-plugin ---
[INFO] Generating /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/test-classes/the.hpl
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:resolve-test-dependencies (default-resolve-test-dependencies) @ jbehave-jenkins-plugin ---
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ jbehave-jenkins-plugin ---
[INFO] Surefire report directory: /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jbehave.jenkins.ReportTransformBehaviour
Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story all_successful.story
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="all_successful.story" tests="3" time="0" failures="0" errors="0"
           skipped="0">
   <testcase name="A simple successful scenario"/>
   <testcase name="Another simple successful scenario"/>
   <testcase name="Yet another simple successful scenario"/>
</testsuite>Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story failure_followed_by_given_story.story
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="failure_followed_by_given_story.story" tests="2" time="0" failures="1"
           errors="0"
           skipped="0">
   <testcase name="A simple failure scenario">
      <failure message="When a test fails">java.lang.RuntimeException: Test failed</failure>
   </testcase>
   <testcase name="A simple successful scenario"/>
</testsuite>Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story given_failing_story.story
org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
org.jbehave.core.embedder.PerformableTree$SomethingHappened@a6233ca: java.lang.RuntimeException: Test failed
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:553)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:238)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:216)
	at org.jbehave.jenkins.ReportTransformBehaviour.runStories(ReportTransformBehaviour.java:178)
	at org.jbehave.jenkins.ReportTransformBehaviour.transformFailedGivenStoryReport(ReportTransformBehaviour.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="given_failing_story.story" tests="1" time="0" failures="1" errors="0"
           skipped="0">
   <testcase name="A simple successful scenario">
      <failure message="When a test fails">java.lang.RuntimeException: Test failed</failure>
   </testcase>
</testsuite>Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story all_successful.story
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="all_successful.story" tests="3" time="0" failures="0" errors="0"
           skipped="0">
   <testcase name="A simple successful scenario"/>
   <testcase name="Another simple successful scenario"/>
   <testcase name="Yet another simple successful scenario"/>
</testsuite>Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story given_story.story
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="given_story.story" tests="1" time="0" failures="0" errors="0" skipped="0">
   <testcase name="A simple successful scenario"/>
</testsuite>Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story all_failed.story
org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
org.jbehave.core.embedder.PerformableTree$SomethingHappened@449eb687: java.lang.RuntimeException: Test failed
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:553)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:238)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:216)
	at org.jbehave.jenkins.ReportTransformBehaviour.runStories(ReportTransformBehaviour.java:178)
	at org.jbehave.jenkins.ReportTransformBehaviour.transformFailedStoryReport(ReportTransformBehaviour.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="all_failed.story" tests="1" time="0" failures="1" errors="0" skipped="0">
   <testcase name="A simple failing scenario">
      <failure message="When a test fails">java.lang.RuntimeException: Test failed</failure>
   </testcase>
</testsuite>Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story title.story
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="title.story" tests="1" time="0" failures="0" errors="0" skipped="1">
   <testcase name="Something">
      <skipped message="PENDING: When I do something"/>
   </testcase>
</testsuite>Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=false,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeouts=300,threads=1,failOnStoryTimeout=false]
Running story examples_table_with_failure.story
org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
org.jbehave.core.embedder.PerformableTree$SomethingHappened@4ae28d89: java.lang.RuntimeException: When failed
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:553)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:238)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:216)
	at org.jbehave.jenkins.ReportTransformBehaviour.runStories(ReportTransformBehaviour.java:178)
	at org.jbehave.jenkins.ReportTransformBehaviour.transformStoryWithExamplesReport(ReportTransformBehaviour.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="examples_table_with_failure.story" tests="6" time="0" failures="3"
           errors="0"
           skipped="1">
   <testcase name="A scenario with a example table with a single failure {param1=value1, param2=value2, author=Alan}"/>
   <testcase name="A scenario with a example table with a single failure {param1=value1, param2=fail, author=Alan}">
      <failure message="When a test is executed with ">java.lang.RuntimeException: When failed</failure>
   </testcase>
   <testcase name="A scenario with a example table with a single failure {param1=value1, param2=value2, author=Alan}"/>
   <testcase name="A scenario with a example table with a different failure {param1=value1, param2=fail, author=Alan}">
      <failure message="When a test is executed with ">java.lang.RuntimeException: When failed</failure>
   </testcase>
   <testcase name="A scenario with a example table with a different failure {param1=value1, param2=value2, author=Alan}">
      <skipped message="PENDING: Then a tester is pending"/>
   </testcase>
   <testcase name="A scenario with a example table with a different failure {param1=value1, param2=fail, author=Alan}">
      <failure message="When a test is executed with ">java.lang.RuntimeException: When failed</failure>
   </testcase>
</testsuite>Tests run: 10, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 2.332 sec - in org.jbehave.jenkins.ReportTransformBehaviour

Results :

Tests run: 10, Failures: 0, Errors: 0, Skipped: 2

[INFO] 
[INFO] --- maven-hpi-plugin:1.117:hpi (default-hpi) @ jbehave-jenkins-plugin ---
[INFO] Generating /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/jbehave-jenkins-plugin/META-INF/MANIFEST.MF
[INFO] Checking for attached .jar artifact ...
[INFO] Generating jar /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/jbehave-jenkins-plugin.jar
[INFO] Building jar: /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/jbehave-jenkins-plugin.jar
[INFO] Exploding webapp...
[INFO] Copy webapp webResources to /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/jbehave-jenkins-plugin
[INFO] Assembling webapp jbehave-jenkins-plugin in /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/jbehave-jenkins-plugin
[INFO] Generating hpi /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/jbehave-jenkins-plugin.hpi
[INFO] Building jar: /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/jbehave-jenkins-plugin.hpi
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.626 s
[INFO] Finished at: 2016-04-25T13:32:43-04:00
[INFO] Final Memory: 32M/1103M
[INFO] ------------------------------------------------------------------------
```

and 

mvn hpi:test-hpl

```
➜  jbehave-jenkins-plugin git:(jenkins) mvn hpi:test-hpl
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JBehave Jenkins Plugin 4.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:test-hpl (default-cli) @ jbehave-jenkins-plugin ---
[INFO] Generating /home/schristou88/Jenkins/jbehave-core/jbehave-jenkins-plugin/target/test-classes/the.hpl
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.083 s
[INFO] Finished at: 2016-04-25T13:34:00-04:00
[INFO] Final Memory: 28M/937M
[INFO] ------------------------------------------------------------------------
```

**Comment by christ66** [comment]
Closing PR as this was merged as part of: https://github.com/jbehave/jbehave-core/commit/2a910cf7dfd17ad65ac2df8b6bb42d0847e3b79f.

**Pull request closed without merging**
