### PR TITLE
JBEHAVE-1138 GivenStories at story level are reported to StoryReporter chaotically in multi-threaded mode

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by valfirst** [comment]
Is there any chance to review and merge the changes to the master so that they will be included in the upcoming JBehave 4.1 release?

**Comment by maurotalevi** [comment]
The context use for GivenStories was introduced in
https://jbehave.atlassian.net/browse/JBEHAVE-1036

I think your patch would be a regression.

**Comment by valfirst** [comment]
Let me explain my changes. 
Logic before changes:
```java
final boolean parentGivenStory = context.givenStory; // save original givenStory flag
...
context.givenStory = performableStory.givenStory();  // put story givenStory to context
performableStory.perform(context);                   // perform story
...
context.givenStory = parentGivenStory;               // restore original givenStory flag
```
`givenStory` flag from the context is used twice in the `perform` method of PerformableStory class (I didn't find any other usages of this flag during story execution) :
```java
...
context.reporter().beforeStory(story, context.givenStory);
... 
context.reporter().afterStory(context.givenStory);
...
```
But PerformableStory  has own field `givenStory`, so I propose to remove context put-restore operations and use field of the class:
```java
...
context.reporter().beforeStory(story, givenStory);
... 
context.reporter().afterStory(givenStory);
...
```

As for [JBEHAVE-1036](https://jbehave.atlassian.net/browse/JBEHAVE-1036) the corresponding [changes](https://github.com/jbehave/jbehave-core/commit/637f6013952b0ec9359ef6a41937a4f8a908129c#diff-fc07563d61d3bfc34ae8a8e0430ea539) just added missing saving-restoring original givenStory flag

**Comment by valfirst** [comment]
What about described logic? Is there any other potential regression?

**Comment by valfirst** [comment]
@maurotalevi , does the described logic make sense?

**Comment by maurotalevi** [comment]
Yes, we need to test it.   Can you please provide a story that verifies that JBEHAVE-1036 is still valid?

**Comment by valfirst** [comment]
Is there any way to view attachments from https://jbehave.atlassian.net/browse/JBEHAVE-1036? I want to reproduce the issue from this ticket to create a story that will verify the changes. But I can't see the attachments mentioned in the ticket

**Comment by valfirst** [comment]
@maurotalevi , [any comments](https://github.com/jbehave/jbehave-core/pull/107#issuecomment-231687867) ?

**Comment by maurotalevi** [comment]
I'm afraid the attachments got lost in the migration from Codehaus.    

If you could reproduce based on the description it'd be great!

**Comment by valfirst** [comment]
@maurotalevi,  I am not able to reproduce [JBEHAVE-1036](https://jbehave.atlassian.net/browse/JBEHAVE-1036). The proposed changes doesn't break tests and have been tested for a long time (1.5 years) in my framework. So could you please review the changes?

**Comment by valfirst** [comment]
The changes are added to master branch: 1afc013a93ac9d15026ab09e14ffba159ce4d6b3

**Pull request closed without merging**
